{
  'plugins': ['react-prefer-function-component', '@typescript-eslint'],
  'extends':
    [
      'flying-sheep',
      'eslint-config-airbnb/hooks',
      'plugin:@typescript-eslint/recommended',
      'plugin:@typescript-eslint/recommended-requiring-type-checking',
      'plugin:react-prefer-function-component/recommended',
      'plugin:react/jsx-runtime',
      'eslint-config-prettier',
    ],
  'env': { 'browser': true, 'es6': true },
  'parser': '@typescript-eslint/parser',
  'parserOptions': { 'project': true, 'sourceType': 'module', 'ecmaFeatures': { 'jsx': true } },
  'ignorePatterns': ['/dist/*', '/**/*.css.d.ts'],
  'settings': { 'import/external-module-folders': ['.yarn'] },
  'rules':
    {
      'consistent-return': 0,
      'react/jsx-filename-extension': [1, { 'extensions': ['.jsx', '.tsx'] }],
      'import/no-unresolved': 0,
      'import/extensions': 0,
      'import/order':
        [
          2,
          {
            'alphabetize': { 'order': 'asc' },
            'newlines-between': 'always',
            'pathGroups':
              [
                { 'pattern': '@mui/material/**/*', 'group': 'external', 'position': 'after' },
                { 'pattern': '@mui/icons-material/**/*', 'group': 'external', 'position': 'after' },
              ],
            'pathGroupsExcludedImportTypes': [],
          },
        ],
      'no-continue': 0,
      'no-shadow': 0,
      '@typescript-eslint/no-shadow': 'error',
      'no-use-before-define': 0,
      'dot-notation': 0,
      '@typescript-eslint/dot-notation': ['error', { 'allowIndexSignaturePropertyAccess': false }],
      '@typescript-eslint/no-unused-vars': ['error', { 'ignoreRestSiblings': true }],
      '@typescript-eslint/no-non-null-assertion': 0,
      '@typescript-eslint/member-delimiter-style':
        ['error', { 'singleline': { 'delimiter': 'comma' }, 'multiline': { 'delimiter': 'none' } }],
      'react/function-component-definition': [2, { 'namedComponents': 'arrow-function' }],
      'react/require-default-props': 0,
      'react/jsx-props-no-spreading': 0,
    },
  'root': true,
}
