plugins:
  - '@typescript-eslint'
  - import
  - react
  - react-hooks
  - react-prefer-function-component
extends:
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:react-prefer-function-component/recommended
env:
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  sourceType: module
  ecmaFeatures:
    jsx: true
ignorePatterns: [/dist/*, /**/*.css.d.ts]
settings:
  import/external-module-folders: [.yarn]
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: '^_'
  import/no-unresolved: 0 # handled by TS itself
  import/order:
    - error
    - alphabetize:
        order: asc
      newlines-between: always
      pathGroups:
        - pattern: '@mui/system/**/*'
          group: external
          position: after
        - pattern: '@mui/material/**/*'
          group: external
          position: after
        - pattern: '@mui/icons-material/**/*'
          group: external
          position: after
      pathGroupsExcludedImportTypes: []
root: true
