repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.47.0
    hooks:
      - id: eslint
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@6.4.0'
          - '@typescript-eslint/parser@6.4.0'
          - eslint@8.47.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-flying-sheep@5.2.0
          - eslint-config-prettier@9.0.0
          - eslint-plugin-import@2.27.5
          - eslint-plugin-jsx-a11y@6.7.1
          - eslint-plugin-no-foreach@1.0.0
          - eslint-plugin-react@7.33.1
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-prefer-function-component@3.1.0
