semi: false
singleQuote: true
overrides:
  # JSON with comments and trailing commas
  - files:
      - .vscode/*.json
      - tsconfig.json
    options:
      parser: json5
      quoteProps: preserve
      singleQuote: false
