compressionLevel: mixed

enableGlobalCache: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs

packageExtensions:
  react-plotly.js@*:
    peerDependenciesMeta:
      plotly.js:
        optional: true # if one uses createPlotlyComponent
