name: Dedupe Dependabot PRs

on:
  push:
    branches: ['dependabot/**']

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  dedupe:
    name: Dedupe Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Get bot token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SPENCER_APP_ID  }}
          private_key: ${{ secrets.SPENCER_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.create_token.outputs.token }}
          fetch-depth: 0
          filter: blob:none
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: corepack enable
      - run: yarn dedupe
        env:
          HUSKY: 0
      - name: Commit autofixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[dependabot skip] Dedupe dependencies'
          commit_user_name: spencer-hobson[bot]
          commit_user_email: 149329160+spencer-hobson[bot]@users.noreply.github.com
      - run: git push
